# Generated by Django 5.0.4 on 2024-04-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_attribute_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together=set(),
        ),
    ]
