# Generated by Django 5.0.4 on 2024-04-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_attributevalue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
    ]
