# Generated by Django 5.0.4 on 2024-04-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
