# Generated by Django 5.0.4 on 2024-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
