# Generated by Django 5.0.4 on 2024-04-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send private email to customers')]},
        ),
    ]
